// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  deleteUserAttributeValue,
  getAccount,
  getAttributes,
  getPrivateAttributes,
  getPublicAttributes,
  getAllAttributeCategories,
  getAttributeCategoryWithValues,
  updateAvatar,
  updatePublicAccount,
  upsertUserAttributeValue,
} from "~/modules/account/account.service";

export const registerAccountTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "account_deleteUserAttributeValue",
    {
      description: "delete user attribute value",
      inputSchema: z.object({
      args: z.object({
    userAttributeId: z.string(),
    userAttributeValueId: z.string()
  }),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteUserAttributeValue(ctx.client, { ...params.args, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: account_deleteUserAttributeValue"),
  );

  server.registerTool(
    "account_getAccount",
    {
      description: "get account",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccount(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: account_getAccount"),
  );

  server.registerTool(
    "account_getAttributes",
    {
      description: "get attributes",
      inputSchema: z.object({
      isPublic: z.boolean(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAttributes(ctx.client, ctx.userId, ctx.companyId, params.isPublic);
      return toMcpResult(result);
    }, "Failed: account_getAttributes"),
  );

  server.registerTool(
    "account_getPrivateAttributes",
    {
      description: "get private attributes",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPrivateAttributes(ctx.client, ctx.userId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: account_getPrivateAttributes"),
  );

  server.registerTool(
    "account_getPublicAttributes",
    {
      description: "get public attributes",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPublicAttributes(ctx.client, ctx.userId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: account_getPublicAttributes"),
  );

  server.registerTool(
    "account_getAllAttributeCategories",
    {
      description: "get all attribute categories",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAllAttributeCategories(ctx.client, ctx.userId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: account_getAllAttributeCategories"),
  );

  server.registerTool(
    "account_getAttributeCategoryWithValues",
    {
      description: "get attribute category with values",
      inputSchema: z.object({
      categoryId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAttributeCategoryWithValues(ctx.client, params.categoryId, ctx.userId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: account_getAttributeCategoryWithValues"),
  );

  server.registerTool(
    "account_updateAvatar",
    {
      description: "update avatar",
      inputSchema: z.object({
      avatarUrl: z.string().nullable(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAvatar(ctx.client, ctx.userId, params.avatarUrl);
      return toMcpResult(result);
    }, "Failed: account_updateAvatar"),
  );

  server.registerTool(
    "account_updatePublicAccount",
    {
      description: "update public account",
      inputSchema: z.object({
      account: z.object({
    id: z.string(),
    firstName: z.string(),
    lastName: z.string(),
    about: z.string().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePublicAccount(ctx.client, params.account);
      return toMcpResult(result);
    }, "Failed: account_updatePublicAccount"),
  );

  server.registerTool(
    "account_upsertUserAttributeValue",
    {
      description: "upsert user attribute value",
      inputSchema: z.object({
      update: z.object({
    userAttributeValueId: z.any().optional(),
    userAttributeId: z.string(),
    value: z.any(),
    type: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertUserAttributeValue(ctx.client, { ...params.update, userId: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: account_upsertUserAttributeValue"),
  );
};
