// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
export { registerAccountTools } from "./account";
export { registerAccountingTools } from "./accounting";
export { registerDocumentsTools } from "./documents";
export { registerInventoryTools } from "./inventory";
export { registerInvoicingTools } from "./invoicing";
export { registerItemsTools } from "./items";
export { registerPeopleTools } from "./people";
export { registerProductionTools } from "./production";
export { registerPurchasingTools } from "./purchasing";
export { registerQualityTools } from "./quality";
export { registerResourcesTools } from "./resources";
export { registerSalesTools } from "./sales";
export { registerSettingsTools } from "./settings";
export { registerSharedTools } from "./shared";
export { registerUsersTools } from "./users";
