// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  activateGauge,
  deactivateGauge,
  deleteGauge,
  deleteGaugeCalibrationRecord,
  deleteGaugeType,
  deleteIssue,
  deleteIssueAssociation,
  deleteIssueType,
  deleteIssueWorkflow,
  deleteRequiredAction,
  deleteQualityDocument,
  deleteQualityDocumentStep,
  deleteRisk,
  getIssueFromExternalLink,
  getGauge,
  getGauges,
  getGaugesList,
  getGaugeCalibrationRecord,
  getGaugeCalibrationRecords,
  getGaugeCalibrationRecordsByGaugeId,
  getGaugeTypesList,
  getGaugeType,
  getGaugeTypes,
  getIssue,
  getIssues,
  getIssueWorkflow,
  getIssueAction,
  getIssueActionTasks,
  getIssueApprovalTasks,
  getIssueItems,
  getIssueAssociations,
  getIssueReviewers,
  getIssueSuppliers,
  getIssueTasks,
  getIssueType,
  getIssueTypes,
  getIssueWorkflows,
  getIssueWorkflowsList,
  getIssueTypesList,
  getQualityActions,
  getQualityDocument,
  getQualityDocumentSteps,
  getQualityDocumentVersions,
  getQualityDocuments,
  getQualityDocumentsList,
  getQualityFiles,
  getRequiredActionsList,
  getRequiredActions,
  getRequiredAction,
  getRisk,
  getRisks,
  insertIssueReviewer,
  updateIssueActionProcesses,
  updateIssueStatus,
  updateIssueTaskStatus,
  updateIssueTaskContent,
  updateQualityDocumentStepOrder,
  updateRiskStatus,
  upsertGauge,
  upsertGaugeCalibrationRecord,
  upsertGaugeType,
  upsertIssue,
  upsertIssueWorkflow,
  upsertIssueType,
  upsertRequiredAction,
  upsertQualityDocument,
  upsertQualityDocumentStep,
  upsertRisk,
  getInspectionDocuments,
  getInspectionDocument,
  upsertInspectionDocument,
  deleteInspectionDocument,
  getBalloons,
  getInspectionFeatures,
  getInspectionPlan,
  saveInspectionDocumentAtomic,
} from "~/modules/quality/quality.service";
import {
  nonConformanceReviewerValidator,
  gaugeValidator,
  gaugeCalibrationRecordValidator,
  gaugeTypeValidator,
  issueValidator,
  issueWorkflowValidator,
  issueTypeValidator,
  qualityDocumentValidator,
  qualityDocumentStepValidator,
  riskRegisterValidator,
  inspectionDocumentValidator,
} from "~/modules/quality/quality.models";

export const registerQualityTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "quality_activateGauge",
    {
      description: "activate gauge",
      inputSchema: z.object({
      gaugeId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await activateGauge(ctx.client, params.gaugeId);
      return toMcpResult(result);
    }, "Failed: quality_activateGauge"),
  );

  server.registerTool(
    "quality_deactivateGauge",
    {
      description: "deactivate gauge",
      inputSchema: z.object({
      gaugeId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deactivateGauge(ctx.client, params.gaugeId);
      return toMcpResult(result);
    }, "Failed: quality_deactivateGauge"),
  );

  server.registerTool(
    "quality_deleteGauge",
    {
      description: "delete gauge",
      inputSchema: z.object({
      gaugeId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteGauge(ctx.client, params.gaugeId);
      return toMcpResult(result);
    }, "Failed: quality_deleteGauge"),
  );

  server.registerTool(
    "quality_deleteGaugeCalibrationRecord",
    {
      description: "delete gauge calibration record",
      inputSchema: z.object({
      gaugeCalibrationRecordId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteGaugeCalibrationRecord(ctx.client, params.gaugeCalibrationRecordId);
      return toMcpResult(result);
    }, "Failed: quality_deleteGaugeCalibrationRecord"),
  );

  server.registerTool(
    "quality_deleteGaugeType",
    {
      description: "delete gauge type",
      inputSchema: z.object({
      gaugeTypeId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteGaugeType(ctx.client, params.gaugeTypeId);
      return toMcpResult(result);
    }, "Failed: quality_deleteGaugeType"),
  );

  server.registerTool(
    "quality_deleteIssue",
    {
      description: "delete issue",
      inputSchema: z.object({
      nonConformanceId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteIssue(ctx.client, params.nonConformanceId);
      return toMcpResult(result);
    }, "Failed: quality_deleteIssue"),
  );

  server.registerTool(
    "quality_deleteIssueAssociation",
    {
      description: "delete issue association",
      inputSchema: z.object({
      type: z.string(),
      associationId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteIssueAssociation(ctx.client, params.type, params.associationId);
      return toMcpResult(result);
    }, "Failed: quality_deleteIssueAssociation"),
  );

  server.registerTool(
    "quality_deleteIssueType",
    {
      description: "delete issue type",
      inputSchema: z.object({
      nonConformanceTypeId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteIssueType(ctx.client, params.nonConformanceTypeId);
      return toMcpResult(result);
    }, "Failed: quality_deleteIssueType"),
  );

  server.registerTool(
    "quality_deleteIssueWorkflow",
    {
      description: "delete issue workflow",
      inputSchema: z.object({
      nonConformanceWorkflowId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteIssueWorkflow(ctx.client, params.nonConformanceWorkflowId);
      return toMcpResult(result);
    }, "Failed: quality_deleteIssueWorkflow"),
  );

  server.registerTool(
    "quality_deleteRequiredAction",
    {
      description: "delete required action",
      inputSchema: z.object({
      requiredActionId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteRequiredAction(ctx.client, params.requiredActionId);
      return toMcpResult(result);
    }, "Failed: quality_deleteRequiredAction"),
  );

  server.registerTool(
    "quality_deleteQualityDocument",
    {
      description: "delete quality document",
      inputSchema: z.object({
      qualityDocumentId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteQualityDocument(ctx.client, params.qualityDocumentId);
      return toMcpResult(result);
    }, "Failed: quality_deleteQualityDocument"),
  );

  server.registerTool(
    "quality_deleteQualityDocumentStep",
    {
      description: "delete quality document step",
      inputSchema: z.object({
      qualityDocumentStepId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteQualityDocumentStep(ctx.client, params.qualityDocumentStepId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_deleteQualityDocumentStep"),
  );

  server.registerTool(
    "quality_deleteRisk",
    {
      description: "delete risk",
      inputSchema: z.object({
      riskId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteRisk(ctx.client, params.riskId);
      return toMcpResult(result);
    }, "Failed: quality_deleteRisk"),
  );

  server.registerTool(
    "quality_getIssueFromExternalLink",
    {
      description: "get issue from external link",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueFromExternalLink(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: quality_getIssueFromExternalLink"),
  );

  server.registerTool(
    "quality_getGauge",
    {
      description: "get gauge",
      inputSchema: z.object({
      gaugeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGauge(ctx.client, params.gaugeId);
      return toMcpResult(result);
    }, "Failed: quality_getGauge"),
  );

  server.registerTool(
    "quality_getGauges",
    {
      description: "get gauges",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGauges(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getGauges"),
  );

  server.registerTool(
    "quality_getGaugesList",
    {
      description: "get gauges list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGaugesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getGaugesList"),
  );

  server.registerTool(
    "quality_getGaugeCalibrationRecord",
    {
      description: "get gauge calibration record",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGaugeCalibrationRecord(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: quality_getGaugeCalibrationRecord"),
  );

  server.registerTool(
    "quality_getGaugeCalibrationRecords",
    {
      description: "get gauge calibration records",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGaugeCalibrationRecords(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getGaugeCalibrationRecords"),
  );

  server.registerTool(
    "quality_getGaugeCalibrationRecordsByGaugeId",
    {
      description: "get gauge calibration records by gauge id",
      inputSchema: z.object({
      gaugeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGaugeCalibrationRecordsByGaugeId(ctx.client, params.gaugeId);
      return toMcpResult(result);
    }, "Failed: quality_getGaugeCalibrationRecordsByGaugeId"),
  );

  server.registerTool(
    "quality_getGaugeTypesList",
    {
      description: "get gauge types list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGaugeTypesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getGaugeTypesList"),
  );

  server.registerTool(
    "quality_getGaugeType",
    {
      description: "get gauge type",
      inputSchema: z.object({
      gaugeTypeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGaugeType(ctx.client, params.gaugeTypeId);
      return toMcpResult(result);
    }, "Failed: quality_getGaugeType"),
  );

  server.registerTool(
    "quality_getGaugeTypes",
    {
      description: "get gauge types",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGaugeTypes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getGaugeTypes"),
  );

  server.registerTool(
    "quality_getIssue",
    {
      description: "get issue",
      inputSchema: z.object({
      nonConformanceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssue(ctx.client, params.nonConformanceId);
      return toMcpResult(result);
    }, "Failed: quality_getIssue"),
  );

  server.registerTool(
    "quality_getIssues",
    {
      description: "get issues",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssues(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getIssues"),
  );

  server.registerTool(
    "quality_getIssueWorkflow",
    {
      description: "get issue workflow",
      inputSchema: z.object({
      nonConformanceWorkflowId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueWorkflow(ctx.client, params.nonConformanceWorkflowId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueWorkflow"),
  );

  server.registerTool(
    "quality_getIssueAction",
    {
      description: "get issue action",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueAction(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: quality_getIssueAction"),
  );

  server.registerTool(
    "quality_getIssueActionTasks",
    {
      description: "get issue action tasks",
      inputSchema: z.object({
      id: z.string(),
      supplierId: z.string().optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueActionTasks(ctx.client, params.id, ctx.companyId, params.supplierId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueActionTasks"),
  );

  server.registerTool(
    "quality_getIssueApprovalTasks",
    {
      description: "get issue approval tasks",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueApprovalTasks(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueApprovalTasks"),
  );

  server.registerTool(
    "quality_getIssueItems",
    {
      description: "get issue items",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueItems(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueItems"),
  );

  server.registerTool(
    "quality_getIssueAssociations",
    {
      description: "get issue associations",
      inputSchema: z.object({
      nonConformanceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueAssociations(ctx.client, params.nonConformanceId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueAssociations"),
  );

  server.registerTool(
    "quality_getIssueReviewers",
    {
      description: "get issue reviewers",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueReviewers(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueReviewers"),
  );

  server.registerTool(
    "quality_getIssueSuppliers",
    {
      description: "get issue suppliers",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueSuppliers(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueSuppliers"),
  );

  server.registerTool(
    "quality_getIssueTasks",
    {
      description: "get issue tasks",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueTasks(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueTasks"),
  );

  server.registerTool(
    "quality_getIssueType",
    {
      description: "get issue type",
      inputSchema: z.object({
      nonConformanceTypeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueType(ctx.client, params.nonConformanceTypeId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueType"),
  );

  server.registerTool(
    "quality_getIssueTypes",
    {
      description: "get issue types",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueTypes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getIssueTypes"),
  );

  server.registerTool(
    "quality_getIssueWorkflows",
    {
      description: "get issue workflows",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueWorkflows(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getIssueWorkflows"),
  );

  server.registerTool(
    "quality_getIssueWorkflowsList",
    {
      description: "get issue workflows list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueWorkflowsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueWorkflowsList"),
  );

  server.registerTool(
    "quality_getIssueTypesList",
    {
      description: "get issue types list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIssueTypesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getIssueTypesList"),
  );

  server.registerTool(
    "quality_getQualityActions",
    {
      description: "get quality actions",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQualityActions(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getQualityActions"),
  );

  server.registerTool(
    "quality_getQualityDocument",
    {
      description: "get quality document",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQualityDocument(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: quality_getQualityDocument"),
  );

  server.registerTool(
    "quality_getQualityDocumentSteps",
    {
      description: "get quality document steps",
      inputSchema: z.object({
      qualityDocumentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQualityDocumentSteps(ctx.client, params.qualityDocumentId);
      return toMcpResult(result);
    }, "Failed: quality_getQualityDocumentSteps"),
  );

  server.registerTool(
    "quality_getQualityDocumentVersions",
    {
      description: "get quality document versions",
      inputSchema: z.object({
      qualityDocument: z.object({
    name: z.string(),
    version: z.number()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQualityDocumentVersions(ctx.client, params.qualityDocument, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getQualityDocumentVersions"),
  );

  server.registerTool(
    "quality_getQualityDocuments",
    {
      description: "get quality documents",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQualityDocuments(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getQualityDocuments"),
  );

  server.registerTool(
    "quality_getQualityDocumentsList",
    {
      description: "get quality documents list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQualityDocumentsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getQualityDocumentsList"),
  );

  server.registerTool(
    "quality_getQualityFiles",
    {
      description: "get quality files",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQualityFiles(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getQualityFiles"),
  );

  server.registerTool(
    "quality_getRequiredActionsList",
    {
      description: "get required actions list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getRequiredActionsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: quality_getRequiredActionsList"),
  );

  server.registerTool(
    "quality_getRequiredActions",
    {
      description: "get required actions",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getRequiredActions(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getRequiredActions"),
  );

  server.registerTool(
    "quality_getRequiredAction",
    {
      description: "get required action",
      inputSchema: z.object({
      requiredActionId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getRequiredAction(ctx.client, params.requiredActionId);
      return toMcpResult(result);
    }, "Failed: quality_getRequiredAction"),
  );

  server.registerTool(
    "quality_getRisk",
    {
      description: "get risk",
      inputSchema: z.object({
      riskId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getRisk(ctx.client, params.riskId);
      return toMcpResult(result);
    }, "Failed: quality_getRisk"),
  );

  server.registerTool(
    "quality_getRisks",
    {
      description: "get risks",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    status: z.any().optional(),
    source: z.any().optional(),
    assignee: z.array(z.string()).optional()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getRisks(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getRisks"),
  );

  server.registerTool(
    "quality_insertIssueReviewer",
    {
      description: "insert issue reviewer",
      inputSchema: z.object({
      reviewer: nonConformanceReviewerValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertIssueReviewer(ctx.client, { ...params.reviewer, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_insertIssueReviewer"),
  );

  server.registerTool(
    "quality_updateIssueActionProcesses",
    {
      description: "update issue action processes",
      inputSchema: z.object({
      args: z.object({
    actionTaskId: z.string(),
    processIds: z.array(z.string())
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateIssueActionProcesses(ctx.client, { ...params.args, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_updateIssueActionProcesses"),
  );

  server.registerTool(
    "quality_updateIssueStatus",
    {
      description: "update issue status",
      inputSchema: z.object({
      update: z.object({
    id: z.string(),
    status: z.any(),
    assignee: z.any(),
    closeDate: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateIssueStatus(ctx.client, { ...params.update, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_updateIssueStatus"),
  );

  server.registerTool(
    "quality_updateIssueTaskStatus",
    {
      description: "update issue task status",
      inputSchema: z.object({
      args: z.object({
    id: z.string(),
    status: z.enum(["Pending", "Completed", "Skipped", "In Progress"]),
    type: z.enum(["investigation", "action", "approval", "review"]),
    assignee: z.string().nullable().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateIssueTaskStatus(ctx.client, { ...params.args, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_updateIssueTaskStatus"),
  );

  server.registerTool(
    "quality_updateIssueTaskContent",
    {
      description: "update issue task content",
      inputSchema: z.object({
      args: z.object({
    id: z.string(),
    type: z.enum(["action", "approval", "review"]),
    content: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateIssueTaskContent(ctx.client, params.args);
      return toMcpResult(result);
    }, "Failed: quality_updateIssueTaskContent"),
  );

  server.registerTool(
    "quality_updateQualityDocumentStepOrder",
    {
      description: "update quality document step order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    sortOrder: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateQualityDocumentStepOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_updateQualityDocumentStepOrder"),
  );

  server.registerTool(
    "quality_updateRiskStatus",
    {
      description: "update risk status",
      inputSchema: z.object({
      riskId: z.string(),
      status: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateRiskStatus(ctx.client, params.riskId, params.status);
      return toMcpResult(result);
    }, "Failed: quality_updateRiskStatus"),
  );

  server.registerTool(
    "quality_upsertGauge",
    {
      description: "upsert gauge",
      inputSchema: z.object({
      gauge: gaugeValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertGauge(ctx.client, { ...params.gauge, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertGauge"),
  );

  server.registerTool(
    "quality_upsertGaugeCalibrationRecord",
    {
      description: "upsert gauge calibration record",
      inputSchema: z.object({
      gaugeCalibrationRecord: gaugeCalibrationRecordValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertGaugeCalibrationRecord(ctx.client, { ...params.gaugeCalibrationRecord, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertGaugeCalibrationRecord"),
  );

  server.registerTool(
    "quality_upsertGaugeType",
    {
      description: "upsert gauge type",
      inputSchema: z.object({
      gaugeType: gaugeTypeValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertGaugeType(ctx.client, { ...params.gaugeType, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertGaugeType"),
  );

  server.registerTool(
    "quality_upsertIssue",
    {
      description: "upsert issue",
      inputSchema: z.object({
      nonConformance: issueValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertIssue(ctx.client, { ...params.nonConformance, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertIssue"),
  );

  server.registerTool(
    "quality_upsertIssueWorkflow",
    {
      description: "upsert issue workflow",
      inputSchema: z.object({
      nonConformanceWorkflow: issueWorkflowValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertIssueWorkflow(ctx.client, { ...params.nonConformanceWorkflow, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertIssueWorkflow"),
  );

  server.registerTool(
    "quality_upsertIssueType",
    {
      description: "upsert issue type",
      inputSchema: z.object({
      nonConformanceType: issueTypeValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertIssueType(ctx.client, { ...params.nonConformanceType, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertIssueType"),
  );

  server.registerTool(
    "quality_upsertRequiredAction",
    {
      description: "upsert required action",
      inputSchema: z.object({
      requiredAction: issueTypeValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertRequiredAction(ctx.client, { ...params.requiredAction, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertRequiredAction"),
  );

  server.registerTool(
    "quality_upsertQualityDocument",
    {
      description: "upsert quality document",
      inputSchema: z.object({
      qualityDocument: qualityDocumentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQualityDocument(ctx.client, { ...params.qualityDocument, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertQualityDocument"),
  );

  server.registerTool(
    "quality_upsertQualityDocumentStep",
    {
      description: "upsert quality document step",
      inputSchema: z.object({
      qualityDocumentStep: qualityDocumentStepValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQualityDocumentStep(ctx.client, { ...params.qualityDocumentStep, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertQualityDocumentStep"),
  );

  server.registerTool(
    "quality_upsertRisk",
    {
      description: "upsert risk",
      inputSchema: z.object({
      risk: riskRegisterValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertRisk(ctx.client, { ...params.risk, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertRisk"),
  );

  server.registerTool(
    "quality_getInspectionDocuments",
    {
      description: "get inspection documents",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getInspectionDocuments(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: quality_getInspectionDocuments"),
  );

  server.registerTool(
    "quality_getInspectionDocument",
    {
      description: "get inspection document",
      inputSchema: {
      id: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getInspectionDocument(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: quality_getInspectionDocument"),
  );

  server.registerTool(
    "quality_upsertInspectionDocument",
    {
      description: "upsert inspection document",
      inputSchema: {
      diagram: inspectionDocumentValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertInspectionDocument(ctx.client, { ...params.diagram, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: quality_upsertInspectionDocument"),
  );

  server.registerTool(
    "quality_deleteInspectionDocument",
    {
      description: "delete inspection document",
      inputSchema: {
      id: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteInspectionDocument(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: quality_deleteInspectionDocument"),
  );

  server.registerTool(
    "quality_getBalloons",
    {
      description: "get balloons",
      inputSchema: {
      inspectionDocumentId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getBalloons(ctx.client, params.inspectionDocumentId);
      return toMcpResult(result);
    }, "Failed: quality_getBalloons"),
  );

  server.registerTool(
    "quality_getInspectionFeatures",
    {
      description: "get inspection document features (characteristics grid)",
      inputSchema: {
        inspectionDocumentId: z.string()
      },
      annotations: READ_ONLY_ANNOTATIONS
    },
    withErrorHandling(async (params) => {
      const result = await getInspectionFeatures(
        ctx.client,
        params.inspectionDocumentId
      );
      return toMcpResult(result);
    }, "Failed: quality_getInspectionFeatures")
  );

  server.registerTool(
    "quality_getInspectionPlan",
    {
      description:
        "get inspection plan; each measurement id/featureId is inspectionFeature id, balloonId set when placed on drawing",
      inputSchema: {
      inspectionDocumentId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getInspectionPlan(ctx.client, params.inspectionDocumentId);
      return toMcpResult(result);
    }, "Failed: quality_getInspectionPlan"),
  );

  server.registerTool(
    "quality_saveInspectionDocumentAtomic",
    {
      description:
        "save inspection document; features {create,update,delete} + balloons geometry {create,update,delete} (delete = unplace)",
      inputSchema: {
      args: z.object({
    inspectionDocumentId: z.string(),
    pdfUrl: z.string().nullable().optional(),
    pageCount: z.number().optional(),
    defaultPageWidth: z.number().optional(),
    defaultPageHeight: z.number().optional(),
    features: z.any().optional(),
    balloons: z.any().optional()
  }),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const { features, balloons, ...rest } = params.args;
      const result = await saveInspectionDocumentAtomic(ctx.client, {
        ...rest,
        features: features ?? { create: [], update: [], delete: [] },
        balloons: balloons ?? { create: [], update: [], delete: [] },
        companyId: ctx.companyId,
        userId: ctx.userId
      });
      return toMcpResult(result);
    }, "Failed: quality_saveInspectionDocumentAtomic"),
  );
};
