// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  activateWorkCenter,
  deleteAbility,
  deleteContractor,
  deleteEmployeeAbility,
  deleteFailureMode,
  deleteLocation,
  deleteMaintenanceDispatch,
  deleteMaintenanceDispatchComment,
  deleteMaintenanceDispatchEvent,
  deleteMaintenanceDispatchItem,
  deleteMaintenanceDispatchWorkCenter,
  deleteMaintenanceSchedule,
  deleteMaintenanceScheduleItem,
  deletePartner,
  activateProcess,
  processDeactivate,
  deleteProcess,
  deleteShift,
  deleteSuggestion,
  deleteTraining,
  deleteTrainingAssignment,
  deleteTrainingQuestion,
  deleteWorkCenter,
  getAbilities,
  getAbilitiesList,
  getAbility,
  getContractor,
  getContractors,
  getEmployeeAbilities,
  getFailureMode,
  getFailureModes,
  getFailureModesList,
  getLocation,
  getLocations,
  getLocationsList,
  getMaintenanceDispatch,
  getMaintenanceDispatchComments,
  getMaintenanceDispatchEvents,
  getMaintenanceDispatchItems,
  getMaintenanceDispatchItemTrackedEntities,
  getMaintenanceDispatches,
  getMaintenanceDispatchesByLocation,
  getMaintenanceDispatchWorkCenters,
  getMaintenanceSchedule,
  getMaintenanceScheduleItems,
  getMaintenanceSchedules,
  getMaintenanceSchedulesByLocation,
  getOutstandingTrainingsForUser,
  getPartner,
  getPartnerBySupplierId,
  getPartners,
  getProcess,
  getProcesses,
  getProcessesList,
  getSuggestion,
  getSuggestions,
  getTraining,
  getTrainingAssignment,
  getTrainingAssignmentForCompletion,
  getTrainingAssignments,
  getTrainingAssignmentStatus,
  getTrainingAssignmentSummary,
  getTrainingQuestions,
  getTrainings,
  getTrainingsList,
  getWorkCenter,
  getWorkCenters,
  getWorkCentersByLocation,
  getWorkCentersList,
  getWorkCentersListWithBlockingStatus,
  insertAbility,
  insertEmployeeAbilities,
  insertTrainingCompletion,
  updateAbility,
  updateSuggestionEmoji,
  updateSuggestionTags,
  updateTrainingQuestionOrder,
  upsertContractor,
  upsertEmployeeAbility,
  upsertFailureMode,
  upsertLocation,
  upsertMaintenanceDispatch,
  upsertMaintenanceDispatchComment,
  upsertMaintenanceDispatchEvent,
  upsertMaintenanceDispatchItem,
  upsertMaintenanceDispatchWorkCenter,
  upsertMaintenanceSchedule,
  upsertMaintenanceScheduleItem,
  upsertPartner,
  upsertProcess,
  upsertTraining,
  upsertTrainingAssignment,
  upsertTrainingQuestion,
  upsertWorkCenter,
} from "~/modules/resources/resources.service";
import {
  failureModeValidator,
  locationValidator,
  maintenanceDispatchValidator,
  maintenanceDispatchCommentValidator,
  maintenanceDispatchEventValidator,
  maintenanceDispatchItemValidator,
  maintenanceDispatchWorkCenterValidator,
  maintenanceScheduleValidator,
  maintenanceScheduleItemValidator,
  partnerValidator,
  processValidator,
  trainingValidator,
  trainingQuestionValidator,
  workCenterValidator,
} from "~/modules/resources/resources.models";

export const registerResourcesTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "resources_activateWorkCenter",
    {
      description: "activate work center",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await activateWorkCenter(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: resources_activateWorkCenter"),
  );

  server.registerTool(
    "resources_deleteAbility",
    {
      description: "delete ability",
      inputSchema: z.object({
      abilityId: z.string(),
      hardDelete: z.boolean().optional(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteAbility(ctx.client, params.abilityId, params.hardDelete);
      return toMcpResult(result);
    }, "Failed: resources_deleteAbility"),
  );

  server.registerTool(
    "resources_deleteContractor",
    {
      description: "delete contractor",
      inputSchema: z.object({
      contractorId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteContractor(ctx.client, params.contractorId);
      return toMcpResult(result);
    }, "Failed: resources_deleteContractor"),
  );

  server.registerTool(
    "resources_deleteEmployeeAbility",
    {
      description: "delete employee ability",
      inputSchema: z.object({
      employeeAbilityId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteEmployeeAbility(ctx.client, params.employeeAbilityId);
      return toMcpResult(result);
    }, "Failed: resources_deleteEmployeeAbility"),
  );

  server.registerTool(
    "resources_deleteFailureMode",
    {
      description: "delete failure mode",
      inputSchema: z.object({
      failureModeId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteFailureMode(ctx.client, params.failureModeId);
      return toMcpResult(result);
    }, "Failed: resources_deleteFailureMode"),
  );

  server.registerTool(
    "resources_deleteLocation",
    {
      description: "delete location",
      inputSchema: z.object({
      locationId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteLocation(ctx.client, params.locationId);
      return toMcpResult(result);
    }, "Failed: resources_deleteLocation"),
  );

  server.registerTool(
    "resources_deleteMaintenanceDispatch",
    {
      description: "delete maintenance dispatch",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceDispatch(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: resources_deleteMaintenanceDispatch"),
  );

  server.registerTool(
    "resources_deleteMaintenanceDispatchComment",
    {
      description: "delete maintenance dispatch comment",
      inputSchema: z.object({
      commentId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceDispatchComment(ctx.client, params.commentId);
      return toMcpResult(result);
    }, "Failed: resources_deleteMaintenanceDispatchComment"),
  );

  server.registerTool(
    "resources_deleteMaintenanceDispatchEvent",
    {
      description: "delete maintenance dispatch event",
      inputSchema: z.object({
      eventId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceDispatchEvent(ctx.client, params.eventId);
      return toMcpResult(result);
    }, "Failed: resources_deleteMaintenanceDispatchEvent"),
  );

  server.registerTool(
    "resources_deleteMaintenanceDispatchItem",
    {
      description: "delete maintenance dispatch item",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceDispatchItem(ctx.client, params.itemId);
      return toMcpResult(result);
    }, "Failed: resources_deleteMaintenanceDispatchItem"),
  );

  server.registerTool(
    "resources_deleteMaintenanceDispatchWorkCenter",
    {
      description: "delete maintenance dispatch work center",
      inputSchema: z.object({
      workCenterId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceDispatchWorkCenter(ctx.client, params.workCenterId);
      return toMcpResult(result);
    }, "Failed: resources_deleteMaintenanceDispatchWorkCenter"),
  );

  server.registerTool(
    "resources_deleteMaintenanceSchedule",
    {
      description: "delete maintenance schedule",
      inputSchema: z.object({
      scheduleId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceSchedule(ctx.client, params.scheduleId);
      return toMcpResult(result);
    }, "Failed: resources_deleteMaintenanceSchedule"),
  );

  server.registerTool(
    "resources_deleteMaintenanceScheduleItem",
    {
      description: "delete maintenance schedule item",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceScheduleItem(ctx.client, params.itemId);
      return toMcpResult(result);
    }, "Failed: resources_deleteMaintenanceScheduleItem"),
  );

  server.registerTool(
    "resources_deletePartner",
    {
      description: "delete partner",
      inputSchema: z.object({
      partnerId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePartner(ctx.client, params.partnerId);
      return toMcpResult(result);
    }, "Failed: resources_deletePartner"),
  );

  server.registerTool(
    "resources_activateProcess",
    {
      description: "activate process",
      inputSchema: z.object({
      processId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await activateProcess(ctx.client, params.processId);
      return toMcpResult(result);
    }, "Failed: resources_activateProcess"),
  );

  server.registerTool(
    "resources_processDeactivate",
    {
      description: "process deactivate",
      inputSchema: z.object({
      processId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await processDeactivate(ctx.client, params.processId);
      return toMcpResult(result);
    }, "Failed: resources_processDeactivate"),
  );

  server.registerTool(
    "resources_deleteProcess",
    {
      description: "delete process",
      inputSchema: z.object({
      processId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteProcess(ctx.client, params.processId);
      return toMcpResult(result);
    }, "Failed: resources_deleteProcess"),
  );

  server.registerTool(
    "resources_deleteShift",
    {
      description: "delete shift",
      inputSchema: z.object({
      shiftId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteShift(ctx.client, params.shiftId);
      return toMcpResult(result);
    }, "Failed: resources_deleteShift"),
  );

  server.registerTool(
    "resources_deleteSuggestion",
    {
      description: "delete suggestion",
      inputSchema: z.object({
      suggestionId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSuggestion(ctx.client, params.suggestionId);
      return toMcpResult(result);
    }, "Failed: resources_deleteSuggestion"),
  );

  server.registerTool(
    "resources_deleteTraining",
    {
      description: "delete training",
      inputSchema: z.object({
      trainingId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteTraining(ctx.client, params.trainingId);
      return toMcpResult(result);
    }, "Failed: resources_deleteTraining"),
  );

  server.registerTool(
    "resources_deleteTrainingAssignment",
    {
      description: "delete training assignment",
      inputSchema: z.object({
      assignmentId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteTrainingAssignment(ctx.client, params.assignmentId);
      return toMcpResult(result);
    }, "Failed: resources_deleteTrainingAssignment"),
  );

  server.registerTool(
    "resources_deleteTrainingQuestion",
    {
      description: "delete training question",
      inputSchema: z.object({
      trainingQuestionId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteTrainingQuestion(ctx.client, params.trainingQuestionId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: resources_deleteTrainingQuestion"),
  );

  server.registerTool(
    "resources_deleteWorkCenter",
    {
      description: "delete work center",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteWorkCenter(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: resources_deleteWorkCenter"),
  );

  server.registerTool(
    "resources_getAbilities",
    {
      description: "get abilities",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAbilities(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getAbilities"),
  );

  server.registerTool(
    "resources_getAbilitiesList",
    {
      description: "get abilities list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAbilitiesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: resources_getAbilitiesList"),
  );

  server.registerTool(
    "resources_getAbility",
    {
      description: "get ability",
      inputSchema: z.object({
      abilityId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAbility(ctx.client, params.abilityId);
      return toMcpResult(result);
    }, "Failed: resources_getAbility"),
  );

  server.registerTool(
    "resources_getContractor",
    {
      description: "get contractor",
      inputSchema: z.object({
      contractorId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getContractor(ctx.client, params.contractorId);
      return toMcpResult(result);
    }, "Failed: resources_getContractor"),
  );

  server.registerTool(
    "resources_getContractors",
    {
      description: "get contractors",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getContractors(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getContractors"),
  );

  server.registerTool(
    "resources_getEmployeeAbilities",
    {
      description: "get employee abilities",
      inputSchema: z.object({
      employeeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getEmployeeAbilities(ctx.client, params.employeeId);
      return toMcpResult(result);
    }, "Failed: resources_getEmployeeAbilities"),
  );

  server.registerTool(
    "resources_getFailureMode",
    {
      description: "get failure mode",
      inputSchema: z.object({
      failureModeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getFailureMode(ctx.client, params.failureModeId);
      return toMcpResult(result);
    }, "Failed: resources_getFailureMode"),
  );

  server.registerTool(
    "resources_getFailureModes",
    {
      description: "get failure modes",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getFailureModes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getFailureModes"),
  );

  server.registerTool(
    "resources_getFailureModesList",
    {
      description: "get failure modes list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getFailureModesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: resources_getFailureModesList"),
  );

  server.registerTool(
    "resources_getLocation",
    {
      description: "get location",
      inputSchema: z.object({
      locationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getLocation(ctx.client, params.locationId);
      return toMcpResult(result);
    }, "Failed: resources_getLocation"),
  );

  server.registerTool(
    "resources_getLocations",
    {
      description: "get locations",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getLocations(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getLocations"),
  );

  server.registerTool(
    "resources_getLocationsList",
    {
      description: "get locations list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getLocationsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: resources_getLocationsList"),
  );

  server.registerTool(
    "resources_getMaintenanceDispatch",
    {
      description: "get maintenance dispatch",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatch(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceDispatch"),
  );

  server.registerTool(
    "resources_getMaintenanceDispatchComments",
    {
      description: "get maintenance dispatch comments",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatchComments(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceDispatchComments"),
  );

  server.registerTool(
    "resources_getMaintenanceDispatchEvents",
    {
      description: "get maintenance dispatch events",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatchEvents(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceDispatchEvents"),
  );

  server.registerTool(
    "resources_getMaintenanceDispatchItems",
    {
      description: "get maintenance dispatch items",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatchItems(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceDispatchItems"),
  );

  server.registerTool(
    "resources_getMaintenanceDispatchItemTrackedEntities",
    {
      description: "get maintenance dispatch item tracked entities",
      inputSchema: z.object({
      maintenanceDispatchItemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatchItemTrackedEntities(ctx.client, params.maintenanceDispatchItemId);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceDispatchItemTrackedEntities"),
  );

  server.registerTool(
    "resources_getMaintenanceDispatches",
    {
      description: "get maintenance dispatches",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    status: z.string().optional()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatches(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceDispatches"),
  );

  server.registerTool(
    "resources_getMaintenanceDispatchesByLocation",
    {
      description: "get maintenance dispatches by location",
      inputSchema: z.object({
      locationId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    status: z.string().optional()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatchesByLocation(ctx.client, ctx.companyId, params.locationId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceDispatchesByLocation"),
  );

  server.registerTool(
    "resources_getMaintenanceDispatchWorkCenters",
    {
      description: "get maintenance dispatch work centers",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatchWorkCenters(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceDispatchWorkCenters"),
  );

  server.registerTool(
    "resources_getMaintenanceSchedule",
    {
      description: "get maintenance schedule",
      inputSchema: z.object({
      scheduleId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceSchedule(ctx.client, params.scheduleId);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceSchedule"),
  );

  server.registerTool(
    "resources_getMaintenanceScheduleItems",
    {
      description: "get maintenance schedule items",
      inputSchema: z.object({
      scheduleId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceScheduleItems(ctx.client, params.scheduleId);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceScheduleItems"),
  );

  server.registerTool(
    "resources_getMaintenanceSchedules",
    {
      description: "get maintenance schedules",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    active: z.boolean().optional()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceSchedules(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceSchedules"),
  );

  server.registerTool(
    "resources_getMaintenanceSchedulesByLocation",
    {
      description: "get maintenance schedules by location",
      inputSchema: z.object({
      locationId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    active: z.boolean().optional()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceSchedulesByLocation(ctx.client, ctx.companyId, params.locationId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getMaintenanceSchedulesByLocation"),
  );

  server.registerTool(
    "resources_getOutstandingTrainingsForUser",
    {
      description: "get outstanding trainings for user",
      inputSchema: z.object({
      employeeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOutstandingTrainingsForUser(ctx.client, ctx.companyId, params.employeeId);
      return toMcpResult(result);
    }, "Failed: resources_getOutstandingTrainingsForUser"),
  );

  server.registerTool(
    "resources_getPartner",
    {
      description: "get partner",
      inputSchema: z.object({
      partnerId: z.string(),
      abilityId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPartner(ctx.client, params.partnerId, params.abilityId);
      return toMcpResult(result);
    }, "Failed: resources_getPartner"),
  );

  server.registerTool(
    "resources_getPartnerBySupplierId",
    {
      description: "get partner by supplier id",
      inputSchema: z.object({
      partnerId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPartnerBySupplierId(ctx.client, params.partnerId);
      return toMcpResult(result);
    }, "Failed: resources_getPartnerBySupplierId"),
  );

  server.registerTool(
    "resources_getPartners",
    {
      description: "get partners",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPartners(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getPartners"),
  );

  server.registerTool(
    "resources_getProcess",
    {
      description: "get process",
      inputSchema: z.object({
      processId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProcess(ctx.client, params.processId);
      return toMcpResult(result);
    }, "Failed: resources_getProcess"),
  );

  server.registerTool(
    "resources_getProcesses",
    {
      description: "get processes",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProcesses(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getProcesses"),
  );

  server.registerTool(
    "resources_getProcessesList",
    {
      description: "get processes list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProcessesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: resources_getProcessesList"),
  );

  server.registerTool(
    "resources_getSuggestion",
    {
      description: "get suggestion",
      inputSchema: z.object({
      suggestionId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSuggestion(ctx.client, params.suggestionId);
      return toMcpResult(result);
    }, "Failed: resources_getSuggestion"),
  );

  server.registerTool(
    "resources_getSuggestions",
    {
      description: "get suggestions",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSuggestions(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getSuggestions"),
  );

  server.registerTool(
    "resources_getTraining",
    {
      description: "get training",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTraining(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: resources_getTraining"),
  );

  server.registerTool(
    "resources_getTrainingAssignment",
    {
      description: "get training assignment",
      inputSchema: z.object({
      assignmentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrainingAssignment(ctx.client, params.assignmentId);
      return toMcpResult(result);
    }, "Failed: resources_getTrainingAssignment"),
  );

  server.registerTool(
    "resources_getTrainingAssignmentForCompletion",
    {
      description: "get training assignment for completion",
      inputSchema: z.object({
      assignmentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrainingAssignmentForCompletion(ctx.client, params.assignmentId);
      return toMcpResult(result);
    }, "Failed: resources_getTrainingAssignmentForCompletion"),
  );

  server.registerTool(
    "resources_getTrainingAssignments",
    {
      description: "get training assignments",
      inputSchema: z.object({
      trainingId: z.string().optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrainingAssignments(ctx.client, ctx.companyId, params.trainingId);
      return toMcpResult(result);
    }, "Failed: resources_getTrainingAssignments"),
  );

  server.registerTool(
    "resources_getTrainingAssignmentStatus",
    {
      description: "get training assignment status",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrainingAssignmentStatus(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getTrainingAssignmentStatus"),
  );

  server.registerTool(
    "resources_getTrainingAssignmentSummary",
    {
      description: "get training assignment summary",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrainingAssignmentSummary(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: resources_getTrainingAssignmentSummary"),
  );

  server.registerTool(
    "resources_getTrainingQuestions",
    {
      description: "get training questions",
      inputSchema: z.object({
      trainingId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrainingQuestions(ctx.client, params.trainingId);
      return toMcpResult(result);
    }, "Failed: resources_getTrainingQuestions"),
  );

  server.registerTool(
    "resources_getTrainings",
    {
      description: "get trainings",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrainings(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getTrainings"),
  );

  server.registerTool(
    "resources_getTrainingsList",
    {
      description: "get trainings list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrainingsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: resources_getTrainingsList"),
  );

  server.registerTool(
    "resources_getWorkCenter",
    {
      description: "get work center",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWorkCenter(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: resources_getWorkCenter"),
  );

  server.registerTool(
    "resources_getWorkCenters",
    {
      description: "get work centers",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWorkCenters(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: resources_getWorkCenters"),
  );

  server.registerTool(
    "resources_getWorkCentersByLocation",
    {
      description: "get work centers by location",
      inputSchema: z.object({
      locationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWorkCentersByLocation(ctx.client, params.locationId);
      return toMcpResult(result);
    }, "Failed: resources_getWorkCentersByLocation"),
  );

  server.registerTool(
    "resources_getWorkCentersList",
    {
      description: "get work centers list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWorkCentersList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: resources_getWorkCentersList"),
  );

  server.registerTool(
    "resources_getWorkCentersListWithBlockingStatus",
    {
      description: "get work centers list with blocking status",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWorkCentersListWithBlockingStatus(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: resources_getWorkCentersListWithBlockingStatus"),
  );

  server.registerTool(
    "resources_insertAbility",
    {
      description: "insert ability",
      inputSchema: z.object({
      ability: z.object({
    name: z.string(),
    curve: z.any(),
    data: z.any(),
    week: z.number(),
    value: z.number(),
    shadowWeeks: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertAbility(ctx.client, { ...params.ability, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_insertAbility"),
  );

  server.registerTool(
    "resources_insertEmployeeAbilities",
    {
      description: "insert employee abilities",
      inputSchema: z.object({
      abilityId: z.string(),
      employeeIds: z.array(z.string()),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertEmployeeAbilities(ctx.client, params.abilityId, params.employeeIds, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: resources_insertEmployeeAbilities"),
  );

  server.registerTool(
    "resources_insertTrainingCompletion",
    {
      description: "insert training completion",
      inputSchema: z.object({
      completion: z.object({
    trainingAssignmentId: z.string(),
    employeeId: z.string(),
    period: z.string().nullable(),
    completedBy: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertTrainingCompletion(ctx.client, { ...params.completion, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_insertTrainingCompletion"),
  );

  server.registerTool(
    "resources_updateAbility",
    {
      description: "update ability",
      inputSchema: z.object({
      id: z.string(),
      ability: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAbility(ctx.client, params.id, params.ability);
      return toMcpResult(result);
    }, "Failed: resources_updateAbility"),
  );

  server.registerTool(
    "resources_updateSuggestionEmoji",
    {
      description: "update suggestion emoji",
      inputSchema: z.object({
      suggestionId: z.string(),
      emoji: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSuggestionEmoji(ctx.client, params.suggestionId, params.emoji);
      return toMcpResult(result);
    }, "Failed: resources_updateSuggestionEmoji"),
  );

  server.registerTool(
    "resources_updateSuggestionTags",
    {
      description: "update suggestion tags",
      inputSchema: z.object({
      suggestionId: z.string(),
      tags: z.array(z.string()),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSuggestionTags(ctx.client, params.suggestionId, params.tags);
      return toMcpResult(result);
    }, "Failed: resources_updateSuggestionTags"),
  );

  server.registerTool(
    "resources_updateTrainingQuestionOrder",
    {
      description: "update training question order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    sortOrder: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateTrainingQuestionOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_updateTrainingQuestionOrder"),
  );

  server.registerTool(
    "resources_upsertContractor",
    {
      description: "upsert contractor",
      inputSchema: z.object({
      contractorWithAbilities: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertContractor(ctx.client, { ...params.contractorWithAbilities, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertContractor"),
  );

  server.registerTool(
    "resources_upsertEmployeeAbility",
    {
      description: "upsert employee ability",
      inputSchema: z.object({
      employeeAbility: z.object({
    id: z.string().optional(),
    abilityId: z.string(),
    employeeId: z.string(),
    trainingCompleted: z.boolean(),
    trainingDays: z.number().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertEmployeeAbility(ctx.client, { ...params.employeeAbility, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: resources_upsertEmployeeAbility"),
  );

  server.registerTool(
    "resources_upsertFailureMode",
    {
      description: "upsert failure mode",
      inputSchema: z.object({
      failureMode: failureModeValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertFailureMode(ctx.client, { ...params.failureMode, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertFailureMode"),
  );

  server.registerTool(
    "resources_upsertLocation",
    {
      description: "upsert location",
      inputSchema: z.object({
      location: locationValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertLocation(ctx.client, { ...params.location, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertLocation"),
  );

  server.registerTool(
    "resources_upsertMaintenanceDispatch",
    {
      description: "upsert maintenance dispatch",
      inputSchema: z.object({
      dispatch: maintenanceDispatchValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceDispatch(ctx.client, { ...params.dispatch, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertMaintenanceDispatch"),
  );

  server.registerTool(
    "resources_upsertMaintenanceDispatchComment",
    {
      description: "upsert maintenance dispatch comment",
      inputSchema: z.object({
      comment: maintenanceDispatchCommentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceDispatchComment(ctx.client, { ...params.comment, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertMaintenanceDispatchComment"),
  );

  server.registerTool(
    "resources_upsertMaintenanceDispatchEvent",
    {
      description: "upsert maintenance dispatch event",
      inputSchema: z.object({
      event: maintenanceDispatchEventValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceDispatchEvent(ctx.client, { ...params.event, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertMaintenanceDispatchEvent"),
  );

  server.registerTool(
    "resources_upsertMaintenanceDispatchItem",
    {
      description: "upsert maintenance dispatch item",
      inputSchema: z.object({
      item: maintenanceDispatchItemValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceDispatchItem(ctx.client, { ...params.item, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertMaintenanceDispatchItem"),
  );

  server.registerTool(
    "resources_upsertMaintenanceDispatchWorkCenter",
    {
      description: "upsert maintenance dispatch work center",
      inputSchema: z.object({
      workCenter: maintenanceDispatchWorkCenterValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceDispatchWorkCenter(ctx.client, { ...params.workCenter, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertMaintenanceDispatchWorkCenter"),
  );

  server.registerTool(
    "resources_upsertMaintenanceSchedule",
    {
      description: "upsert maintenance schedule",
      inputSchema: z.object({
      schedule: maintenanceScheduleValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceSchedule(ctx.client, { ...params.schedule, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertMaintenanceSchedule"),
  );

  server.registerTool(
    "resources_upsertMaintenanceScheduleItem",
    {
      description: "upsert maintenance schedule item",
      inputSchema: z.object({
      item: maintenanceScheduleItemValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceScheduleItem(ctx.client, { ...params.item, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertMaintenanceScheduleItem"),
  );

  server.registerTool(
    "resources_upsertPartner",
    {
      description: "upsert partner",
      inputSchema: z.object({
      partner: partnerValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPartner(ctx.client, { ...params.partner, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertPartner"),
  );

  server.registerTool(
    "resources_upsertProcess",
    {
      description: "upsert process",
      inputSchema: z.object({
      process: processValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertProcess(ctx.client, { ...params.process, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertProcess"),
  );

  server.registerTool(
    "resources_upsertTraining",
    {
      description: "upsert training",
      inputSchema: z.object({
      training: trainingValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertTraining(ctx.client, { ...params.training, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertTraining"),
  );

  server.registerTool(
    "resources_upsertTrainingAssignment",
    {
      description: "upsert training assignment",
      inputSchema: z.object({
      assignment: z.object({
    id: z.string().optional(),
    trainingId: z.string(),
    groupIds: z.array(z.string())
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertTrainingAssignment(ctx.client, { ...params.assignment, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertTrainingAssignment"),
  );

  server.registerTool(
    "resources_upsertTrainingQuestion",
    {
      description: "upsert training question",
      inputSchema: z.object({
      trainingQuestion: trainingQuestionValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertTrainingQuestion(ctx.client, { ...params.trainingQuestion, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertTrainingQuestion"),
  );

  server.registerTool(
    "resources_upsertWorkCenter",
    {
      description: "upsert work center",
      inputSchema: z.object({
      workCenter: workCenterValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertWorkCenter(ctx.client, { ...params.workCenter, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: resources_upsertWorkCenter"),
  );
};
