// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  deleteEmployeeType,
  deleteGroup,
  getCompaniesForUser,
  getCustomers,
  getEmployee,
  getEmployees,
  getConsoleOperators,
  getEmployeeType,
  getEmployeeTypes,
  getInvitable,
  getModules,
  getGroup,
  getGroupMembers,
  getGroups,
  getGroupEmails,
  getPermissionsByEmployeeType,
  getSuppliers,
  getUsers,
  getUserEmails,
  insertEmployeeType,
  insertGroup,
  upsertEmployeeType,
  upsertEmployeeTypePermissions,
  upsertGroup,
  upsertGroupMembers,
} from "~/modules/users/users.service";

export const registerUsersTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "users_deleteEmployeeType",
    {
      description: "delete employee type",
      inputSchema: z.object({
      employeeTypeId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteEmployeeType(ctx.client, params.employeeTypeId);
      return toMcpResult(result);
    }, "Failed: users_deleteEmployeeType"),
  );

  server.registerTool(
    "users_deleteGroup",
    {
      description: "delete group",
      inputSchema: z.object({
      groupId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteGroup(ctx.client, params.groupId);
      return toMcpResult(result);
    }, "Failed: users_deleteGroup"),
  );

  server.registerTool(
    "users_getCompaniesForUser",
    {
      description: "get companies for user",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCompaniesForUser(ctx.client, ctx.userId);
      return toMcpResult(result);
    }, "Failed: users_getCompaniesForUser"),
  );

  server.registerTool(
    "users_getCustomers",
    {
      description: "get customers",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomers(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: users_getCustomers"),
  );

  server.registerTool(
    "users_getEmployee",
    {
      description: "get employee",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getEmployee(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: users_getEmployee"),
  );

  server.registerTool(
    "users_getEmployees",
    {
      description: "get employees",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getEmployees(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: users_getEmployees"),
  );

  server.registerTool(
    "users_getConsoleOperators",
    {
      description: "get console operators",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getConsoleOperators(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: users_getConsoleOperators"),
  );

  server.registerTool(
    "users_getEmployeeType",
    {
      description: "get employee type",
      inputSchema: z.object({
      employeeTypeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getEmployeeType(ctx.client, params.employeeTypeId);
      return toMcpResult(result);
    }, "Failed: users_getEmployeeType"),
  );

  server.registerTool(
    "users_getEmployeeTypes",
    {
      description: "get employee types",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getEmployeeTypes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: users_getEmployeeTypes"),
  );

  server.registerTool(
    "users_getInvitable",
    {
      description: "get invitable",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getInvitable(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: users_getInvitable"),
  );

  server.registerTool(
    "users_getModules",
    {
      description: "get modules",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getModules(ctx.client);
      return toMcpResult(result);
    }, "Failed: users_getModules"),
  );

  server.registerTool(
    "users_getGroup",
    {
      description: "get group",
      inputSchema: z.object({
      groupId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGroup(ctx.client, params.groupId);
      return toMcpResult(result);
    }, "Failed: users_getGroup"),
  );

  server.registerTool(
    "users_getGroupMembers",
    {
      description: "get group members",
      inputSchema: z.object({
      groupId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGroupMembers(ctx.client, params.groupId);
      return toMcpResult(result);
    }, "Failed: users_getGroupMembers"),
  );

  server.registerTool(
    "users_getGroups",
    {
      description: "get groups",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    uid: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGroups(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: users_getGroups"),
  );

  server.registerTool(
    "users_getGroupEmails",
    {
      description: "get group emails",
      inputSchema: z.object({
      groupIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGroupEmails(ctx.client, params.groupIds);
      return toMcpResult(result);
    }, "Failed: users_getGroupEmails"),
  );

  server.registerTool(
    "users_getPermissionsByEmployeeType",
    {
      description: "get permissions by employee type",
      inputSchema: z.object({
      employeeTypeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPermissionsByEmployeeType(ctx.client, params.employeeTypeId);
      return toMcpResult(result);
    }, "Failed: users_getPermissionsByEmployeeType"),
  );

  server.registerTool(
    "users_getSuppliers",
    {
      description: "get suppliers",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSuppliers(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: users_getSuppliers"),
  );

  server.registerTool(
    "users_getUsers",
    {
      description: "get users",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getUsers(ctx.client);
      return toMcpResult(result);
    }, "Failed: users_getUsers"),
  );

  server.registerTool(
    "users_getUserEmails",
    {
      description: "get user emails",
      inputSchema: z.object({
      userIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getUserEmails(ctx.client, params.userIds);
      return toMcpResult(result);
    }, "Failed: users_getUserEmails"),
  );

  server.registerTool(
    "users_insertEmployeeType",
    {
      description: "insert employee type",
      inputSchema: z.object({
      employeeType: z.object({
    name: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertEmployeeType(ctx.client, { ...params.employeeType, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: users_insertEmployeeType"),
  );

  server.registerTool(
    "users_insertGroup",
    {
      description: "insert group",
      inputSchema: z.object({
      group: z.object({
    name: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertGroup(ctx.client, { ...params.group, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: users_insertGroup"),
  );

  server.registerTool(
    "users_upsertEmployeeType",
    {
      description: "upsert employee type",
      inputSchema: z.object({
      employeeType: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertEmployeeType(ctx.client, { ...params.employeeType, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: users_upsertEmployeeType"),
  );

  server.registerTool(
    "users_upsertEmployeeTypePermissions",
    {
      description: "upsert employee type permissions",
      inputSchema: z.object({
      employeeTypeId: z.string(),
      permissions: z.object({
    name: z.string(),
    permission: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertEmployeeTypePermissions(ctx.client, params.employeeTypeId, ctx.companyId, params.permissions);
      return toMcpResult(result);
    }, "Failed: users_upsertEmployeeTypePermissions"),
  );

  server.registerTool(
    "users_upsertGroup",
    {
      description: "upsert group",
      inputSchema: z.object({
      arg1: z.object({
    id: z.string(),
    name: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertGroup(ctx.client, { ...params.arg1, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: users_upsertGroup"),
  );

  server.registerTool(
    "users_upsertGroupMembers",
    {
      description: "upsert group members",
      inputSchema: z.object({
      groupId: z.string(),
      selections: z.array(z.string()),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertGroupMembers(ctx.client, params.groupId, params.selections);
      return toMcpResult(result);
    }, "Failed: users_upsertGroupMembers"),
  );
};
