/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */


/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CarbonERPService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "CarbonMESService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "CarbonVpc2": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}